const fs = require('node:fs');
const { initializeTestEnvironment, assertSucceeds, assertFails } = require('@firebase/rules-unit-testing');
const { doc, collection, query, where, getDoc, getDocs, setDoc, updateDoc, deleteDoc, writeBatch, serverTimestamp } = require('firebase/firestore');

(async () => {
    const env = await initializeTestEnvironment({ projectId: 'demo-demonlist', firestore: { host: '127.0.0.1', port: 8080, rules: fs.readFileSync('firestore.rules','utf8') } });
    let passed = 0;
    const check = async (label, promise, allowed) => { await (allowed ? assertSucceeds(promise) : assertFails(promise)); ++passed; console.log('PASS',label); };
    const level = { name:'Emulator level', position:1, points:50, creator:'Creator', verifier:'Verifier', levelUrl:'https://example.org/level', proofUrl:'https://example.org/proof' };
    const record = { player:'Player',playerId:'player-a',levelId:'level-a',progress:100,approved:true };
    try {
        await env.withSecurityRulesDisabled(async context => {
            const db=context.firestore();
            await setDoc(doc(db,'levels','level-a'),level);
            await setDoc(doc(db,'records','record-a'),record);
            await setDoc(doc(db,'records','private-record'),{...record,approved:false});
        });
        const guest=env.unauthenticatedContext().firestore();
        const player=env.authenticatedContext('player-a',{firebase:{sign_in_provider:'google.com'}}).firestore();
        const other=env.authenticatedContext('player-b',{firebase:{sign_in_provider:'google.com'}}).firestore();
        const admin=env.authenticatedContext('staff-a',{admin:true,firebase:{sign_in_provider:'google.com'}}).firestore();
        const passwordAdmin=env.authenticatedContext('staff-b',{admin:true,firebase:{sign_in_provider:'password'}}).firestore();
        await check('public level reads',getDoc(doc(guest,'levels','level-a')),true);
        await check('approved records query',getDocs(query(collection(guest,'records'),where('approved','==',true))),true);
        await check('unapproved record stays private',getDoc(doc(guest,'records','private-record')),false);
        await check('guest cannot publish a level',setDoc(doc(guest,'levels','guest-level'),level),false);
        await check('guest cannot approve a record',setDoc(doc(guest,'records','guest-record'),record),false);
        await check('member cannot publish a level',setDoc(doc(player,'levels','member-level'),level),false);
        await check('member cannot approve a record',setDoc(doc(player,'records','member-record'),record),false);
        await check('Google provider is required even for staff',setDoc(doc(passwordAdmin,'levels','password-level'),level),false);
        await check('profile requires rules agreement',setDoc(doc(player,'profiles','player-a'),{displayName:'Player A',bio:'',updatedAt:serverTimestamp()}),false);
        await check('correct agreement version',setDoc(doc(player,'agreements','player-a'),{version:'2026-10-05',acceptedAt:serverTimestamp()}),true);
        await check('profile save after agreement',setDoc(doc(player,'profiles','player-a'),{displayName:'Player A',bio:'',updatedAt:serverTimestamp()}),true);
        await check('profile owner can read it',getDoc(doc(player,'profiles','player-a')),true);
        await check('another user cannot read a private profile',getDoc(doc(other,'profiles','player-a')),false);
        await check('staff cannot read private player profiles',getDoc(doc(admin,'profiles','player-a')),false);
        await check('cannot forge another user agreement',setDoc(doc(player,'agreements','player-b'),{version:'2026-10-05',acceptedAt:serverTimestamp()}),false);
        await check('outdated agreement version rejected',setDoc(doc(player,'agreements','player-a'),{version:'old',acceptedAt:serverTimestamp()}),false);
        const publicProfile={displayName:'Player A',bio:'',tags:['Player','Creator'],updatedAt:serverTimestamp()};
        await check('guest cannot register a public player',setDoc(doc(guest,'players','player-a'),publicProfile),false);
        await check('public profile requires rules agreement',setDoc(doc(other,'players','player-b'),publicProfile),false);
        await check('cannot publish another player profile',setDoc(doc(player,'players','player-b'),publicProfile),false);
        await check('cannot self-assign staff tag',setDoc(doc(player,'players','player-a'),{...publicProfile,tags:['Admin']}),false);
        await check('cannot self-assign points',setDoc(doc(player,'players','player-a'),{...publicProfile,points:999}),false);
        await check('cannot publish email or private fields',setDoc(doc(player,'players','player-a'),{...publicProfile,email:'private@example.org'}),false);
        await check('empty tags rejected',setDoc(doc(player,'players','player-a'),{...publicProfile,tags:[]}),false);
        await check('duplicate tags rejected',setDoc(doc(player,'players','player-a'),{...publicProfile,tags:['Player','Player']}),false);
        await check('public profile must match private player name',setDoc(doc(player,'players','player-a'),{...publicProfile,displayName:'Different name'}),false);
        await check('member publishes their own valid public profile',setDoc(doc(player,'players','player-a'),publicProfile),true);
        await check('optional profile country is accepted',setDoc(doc(player,'players','player-a'),{...publicProfile,country:'FR'}),true);
        await check('unknown profile country is denied',setDoc(doc(player,'players','player-a'),{...publicProfile,country:'ZZ'}),false);
        await check('free-text profile country is denied',setDoc(doc(player,'players','player-a'),{...publicProfile,country:'France'}),false);
        await check('non-string profile country is denied',setDoc(doc(player,'players','player-a'),{...publicProfile,country:12}),false);
        await check('guest can list public players',getDocs(collection(guest,'players')),true);
        await check('another member cannot update a player',updateDoc(doc(other,'players','player-a'),{bio:'Forged'}),false);
        await check('cannot add a privileged field later',updateDoc(doc(player,'players','player-a'),{admin:true}),false);
        await check('public profile must match private bio',updateDoc(doc(player,'players','player-a'),{bio:'Changed',updatedAt:serverTimestamp()}),false);
        const batch=writeBatch(player);
        batch.set(doc(player,'profiles','player-a'),{displayName:'Updated Player',bio:'Public bio',updatedAt:serverTimestamp()});
        batch.set(doc(player,'players','player-a'),{displayName:'Updated Player',bio:'Public bio',tags:['Verifier'],updatedAt:serverTimestamp()});
        await check('profile and directory update atomically using getAfter',batch.commit(),true);
        const badBatch=writeBatch(player);
        badBatch.set(doc(player,'profiles','player-a'),{displayName:'Should not save',bio:'',updatedAt:serverTimestamp()});
        badBatch.set(doc(player,'players','player-a'),{displayName:'Should not save',bio:'',tags:['Owner'],updatedAt:serverTimestamp()});
        await check('invalid public profile rejects the entire batch',badBatch.commit(),false);
        if((await getDoc(doc(player,'profiles','player-a'))).data().displayName!=='Updated Player') throw new Error('Failed batch modified private profile');
        await check('cannot delete another player',deleteDoc(doc(other,'players','player-a')),false);
        const submission={ownerUid:'player-a',submittedBy:'Player A',levelName:'Submitted level',levelUrl:'https://example.org/level',creator:'Creator',verifier:'Verifier',proofUrl:'https://example.org/proof',notes:'',status:'pending',submittedAt:serverTimestamp()};
        await check('signed-in member creates a pending submission',setDoc(doc(player,'submissions','submission-a'),submission),true);
        await check('pending submission accepts an optional country',setDoc(doc(player,'submissions','country-submission'),{...submission,country:'FR'}),true);
        await check('pending submission rejects unknown country',setDoc(doc(player,'submissions','bad-country'),{...submission,country:'ZZ'}),false);
        await check('pending submission rejects non-string country',setDoc(doc(player,'submissions','country-number'),{...submission,country:12}),false);
        await check('country submission stays private from other players',getDoc(doc(other,'submissions','country-submission')),false);
        await check('cannot submit as another user',setDoc(doc(player,'submissions','forged'),{...submission,ownerUid:'player-b'}),false);
        await check('cannot self-approve a new submission',setDoc(doc(player,'submissions','approved'),{...submission,status:'approved'}),false);
        await check('member cannot approve existing submission',updateDoc(doc(player,'submissions','submission-a'),{status:'approved'}),false);
        await check('another member cannot read pending submissions',getDoc(doc(other,'submissions','submission-a')),false);
        await check('owner can list their submissions',getDocs(query(collection(player,'submissions'),where('ownerUid','==','player-a'))),true);
        await check('staff can review pending submissions',getDocs(query(collection(admin,'submissions'),where('status','==','pending'))),true);
        await check('staff publishes a valid level',setDoc(doc(admin,'levels','staff-level'),level),true);
        await check('staff cannot publish incomplete level fields',setDoc(doc(admin,'levels','incomplete'),{name:'Incomplete'}),false);
        await check('staff approves a full completion',setDoc(doc(admin,'records','staff-record'),record),true);
        await check('partial completion rejected by current rules',setDoc(doc(admin,'records','partial'),{...record,progress:99}),false);
        await check('record must reference an existing level',setDoc(doc(admin,'records','missing-level'),{...record,levelId:'not-a-level'}),false);
        console.log(`${passed} Firestore permission checks passed against the proposed rules in the emulator.`);
    } finally { await env.cleanup(); }
})().catch(error=>{console.error(error);process.exitCode=1;});
